name: "solutions"
version: 0.1.0.0
github: "hakula139/99-Haskell-Problems-Solutions"
license: "MIT"
author: "Hakula Chen"
maintainer: "i@hakula.xyz"
copyright: "(c) 2021 Copyright Hakula"

extra-source-files:
  - README.md
  - stack.yaml

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -O2
  - -optc-O3

library:
  source-dirs:
    - src
  exposed-modules:
    - MyUtils
    - Problems.Problem01
    - Problems.Problem02
    - Problems.Problem03
    - Problems.Problem04
    - Problems.Problem05
    - Problems.Problem06
    - Problems.Problem07
    - Problems.Problem08
    - Problems.Problem09
    - Problems.Problem10
    - Problems.Problem11
    - Problems.Problem12
    - Problems.Problem13
    - Problems.Problem14
    - Problems.Problem15
    - Problems.Problem16
    - Problems.Problem17
    - Problems.Problem18

executables:
  solutions-exe:
    main: Main.hs
    source-dirs:
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - solutions
